# 任务基本信息
[task]
name = "qBittorrent-Enhanced-Edition-qt5"
category = "下载上传"
author = "wdw1007"
url = "https://github.com/c0re100/qBittorrent-Enhanced-Edition"

# 指定使用的模板
[template]
scraper = "GitHub_Release"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = 'qbittorrent_enhanced_[0-9,.]{1,}_setup\.exe'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 1
build_manifest = ["${taskName}.wcs","${taskName}"]
build_cover = "build-cover-dir"
build_delete = ['$PLUGINSDIR']

# 爬虫模板临时参数
# [scraper_temp]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "qBittorrent-Enhanced-Edition"
sourceFile = "qbittorrent.exe"
recursiveUnzipList = [ ]


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
weekly = true
